import { acquireAuthenticatedSocket } from '../../../../chat/socket/chatSocket';

const JOB_LIFECYCLE_SOCKET_EVENTS = Object.freeze([
  'JOB_EN_ROUTE',
  'JOB_ARRIVAL_REQUESTED',
  'JOB_ARRIVAL_REJECTED',
  'JOB_ARRIVED',
  'JOB_QUOTE_SUBMITTED',
  'JOB_QUOTE_ACCEPTED',
  'JOB_QUOTE_REJECTED',
  'JOB_PAYMENT_REQUIRED',
  'JOB_PAYMENT_COMPLETED',
  'JOB_IN_PROGRESS',
  'JOB_CANCELLATION_REQUESTED',
  'JOB_CANCELLATION_REVIEW_REQUIRED',
  'JOB_CANCELLATION_REJECTED',
  'JOB_CANCELLED',
  'JOB_COMPLETION_REQUESTED',
  'JOB_COMPLETION_REJECTED',
  'JOB_COMPLETION_CONFIRMED',
  'JOB_WARRANTY_STARTED',
  'JOB_WARRANTY_CLAIM_CREATED',
  'JOB_WARRANTY_REWORK_REQUIRED',
  'JOB_WARRANTY_COMPLETION_REQUESTED',
  'JOB_WARRANTY_REWORK_CONFIRMED',
  'JOB_WARRANTY_REWORK_REJECTED',
  'JOB_WARRANTY_RELEASED',
  'JOB_COMPLETED',
]);

const acquireJobLifecycleSocket = (accessToken) => acquireAuthenticatedSocket(accessToken);

export { JOB_LIFECYCLE_SOCKET_EVENTS, acquireJobLifecycleSocket };
